spring.config.import=classpath:private_data.properties

spring.datasource.url=jdbc:postgresql://${db.host}:${db.port}/${db.name}
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.encoding = UTF-8
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.platform=postgres

#spring.jpa.show-sql=true
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.root=DEBUG
#logging.level.org.springframework.jdbc=DEBUG
#logging.level.org.hibernate=DEBUG
